ci:
  autoupdate_schedule: quarterly

repos:
  - repo: local
    hooks:
      - id: check
        name: make format && mdformat .
        language: system
        entry: uv run make check
        pass_filenames: false
        always_run: true
