[tox]
envlist =
;    py39 ; end of life and gets in the way of minimum pins for lib versions
    py310
    py311
    py312
    py313
    py314

requires =
    tox-uv>=1.28

[testenv]
;extras =
;    fast
deps =
    # parameterized
    pytest>=7.4.4
    toml;python_version<'3.11'
    pytest-benchmark>=4.0.0
    hypothesis>=6.96.0
    pytest_mock
    pytest-xdist>=3.5.0
commands =
    pytest tests -q -n 5
    pytest tests_compatibility -m "not slow"
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
