---
name: tox
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tox:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.13', '3.14'] # , "3.15"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: hynek/setup-cached-uv@4300ec2180bc77d705e626a34e381b81a4772c51  # v2.5.0
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Run tox
        run: tox -e py
